spring.application.name=CriadorFichaRPG

# MySQL / XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/criador_ficha_rpg?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
